---
- hosts: dev
  become: true
  tasks:
    - yum:
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes
    - raw: "echo Welcome to Server | sudo tee /var/www/html/index.html"