// SCRIPTED
// node { stage('Build') {} }
// node { echo "Build" }

// DECLARATIVE
pipeline {
	agent { docker { image 'maven:3.9.7' } }
	environment {
		dockerHome = tool 'myDocker'
		mavenHome = tool 'myMaven'
		PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
	}

	stages {
		stage('Checkout') {
			steps {
				echo "Checkout"
				sh 'mvn --version'
				sh 'docker --version'
				echo "PATH: $PATH"
				echo "BUILD_NUMBER: $env.BUILD_NUMBER"
				echo "BUILD_ID: $env.BUILD_ID"
				echo "JOB_NAME: $env.JOB_NAME"
				echo "BUILD_TAG: $env.BUILD_TAG"
				echo "BUILD_URL: $env.BUILD_URL"
			}
		}

		stage('Compile') {
			steps {
				sh "mvn clean compile"
			}
		}

		stage('Unit Tests') {
			steps {
				sh "mvn test"
			}
		}

		stage('Integration Tests') {
			steps {
				sh "mvn failsafe:integration-test failsafe:verify"
			}
		}
	}
	
	post {
		always {
			echo "Execute always"
		}
		success {
			echo "Executed with success"
		}
		failure {
			echo "Executed with error"
		}
	}
}
