// SCRIPTED
// node { stage('Build') {} }
// node { echo "Build" }

// DECLARATIVE
pipeline {
	agent { docker { image: 'maven:3.6.3' } }
	stages {
		stage('Build') {
			steps {
				sh 'mvn --version'
				echo "Build"
			}
		}
		stage('Test') {
			steps {
				echo "Test"
			}
		}
	}
	
	post {
		always {
			echo "Execute always"
		}
		success {
			echo "Executed with success"
		}
		failure {
			echo "Executed with error"
		}
	}
}
