// SCRIPTED
// node { stage('Build') {} }
// node { echo "Build" }

// DECLARATIVE
pipeline {
	agent { docker { image 'maven:3.6.3' } }
	stages {
		stage('Build') {
			steps {
				echo "Build"
				sh 'mvn --version'
				echo "PATH: $PATH"
				echo "BUILD_NUMBER: $env.BUILD_NUMBER"
				echo "BUILD_ID: $env.BUILD_ID"
				echo "JOB_NAME: $env.JOB_NAME"
				echo "BUILD_TAG: $env.BUILD_TAG"
				echo "BUILD_URL: $env.BUILD_URL"
			}
		}
		stage('Test') {
			steps {
				echo "Test"
			}
		}
	}
	
	post {
		always {
			echo "Execute always"
		}
		success {
			echo "Executed with success"
		}
		failure {
			echo "Executed with error"
		}
	}
}
